export const ABOUT_US = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus mauris a diam maecenas. Ullamcorper eget nulla facilisi etiam dignissim diam. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Elit duis tristique sollicitudin nibh. Ac orci phasellus egestas tellus rutrum tellus. Dictumst vestibulum rhoncus est pellentesque elit. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Interdum posuere lorem ipsum dolor sit amet consectetur. Turpis massa tincidunt dui ut ornare lectus sit. In vitae turpis massa sed elementum tempus egestas sed. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. A diam maecenas sed enim ut sem viverra.

Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Non tellus orci ac auctor augue mauris augue neque. Nulla malesuada pellentesque elit eget. Elementum curabitur vitae nunc sed velit dignissim. Enim nunc faucibus a pellentesque. Fermentum posuere urna nec tincidunt. Laoreet id donec ultrices tincidunt arcu non. Praesent elementum facilisis leo vel. Neque convallis a cras semper auctor. Vitae tempus quam pellentesque nec nam aliquam sem. Eu feugiat pretium nibh ipsum consequat nisl. Quam vulputate dignissim suspendisse in est ante. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Rhoncus est pellentesque elit ullamcorper dignissim cras. Leo in vitae turpis massa. Nam at lectus urna duis convallis convallis tellus id interdum. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida.

Lectus mauris ultrices eros in cursus turpis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Non curabitur gravida arcu ac. Consectetur a erat nam at. Sapien eget mi proin sed libero. Tincidunt arcu non sodales neque sodales ut etiam sit amet. In est ante in nibh mauris cursus mattis molestie a. Eget nunc lobortis mattis aliquam faucibus. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Augue lacus viverra vitae congue eu consequat ac. Morbi tristique senectus et netus et malesuada. Eu mi bibendum neque egestas congue quisque egestas diam. Condimentum lacinia quis vel eros donec. Semper feugiat nibh sed pulvinar proin. Leo duis ut diam quam nulla. Ac turpis egestas sed tempus urna et.

Quis ipsum suspendisse ultrices gravida dictum fusce. Nisl pretium fusce id velit ut tortor. Tristique et egestas quis ipsum. Pharetra magna ac placerat vestibulum. Porta lorem mollis aliquam ut porttitor leo a. Ac turpis egestas integer eget aliquet nibh. Mauris pellentesque pulvinar pellentesque habitant. Tortor id aliquet lectus proin. Nunc congue nisi vitae suscipit. Eleifend donec pretium vulputate sapien nec.

Volutpat diam ut venenatis tellus. Dui id ornare arcu odio ut sem nulla pharetra diam. Felis donec et odio pellentesque diam volutpat. Venenatis cras sed felis eget. Mi quis hendrerit dolor magna eget. Sit amet facilisis magna etiam tempor. Blandit libero volutpat sed cras ornare arcu dui. Eu feugiat pretium nibh ipsum consequat nisl vel. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Velit euismod in pellentesque massa. Mollis nunc sed id semper. In dictum non consectetur a erat nam at lectus urna. Cursus turpis massa tincidunt dui ut. Eget mauris pharetra et ultrices neque. Ac felis donec et odio pellentesque diam volutpat.`;
